CREATE TABLE testdb.PRODUCT
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  cost FLOAT(8,2) NOT NULL
)CHARACTER set utf8;
ALTER TABLE testdb.PRODUCT ADD CONSTRAINT unique_id UNIQUE (id);